#!/usr/bin/env node

var program = require('commander');

program
    .version('0.1.0')
    .command('start [STRATEGY] [TARGET]', 'Start attacking on TARGETS with this STRATEGY')
    .command('help [command]', 'Describe available commands or one specific command')
    .parse(process.argv);

// If invoke without arguments
if (process.argv.length == 2) program.help();
